[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run docs:build']

[start]
# serve static files; Coolify will map PORT
cmd = 'npx http-server .vitepress/dist -p ${PORT:-8080} -c-1'
